'use client'
import { useState, useRef } from "react"
import ChatBubbles from "../chatbubbles/page"
import Image from "next/image"

function ChatPage() {
  type MessageListType = {[key:string]:string}

  const [pageType,setPageType] = useState(1)
  const [message,setMessage] = useState("")
  const [messageList,setMessageList] = useState<MessageListType[]|undefined>([{message:"message by ai can be really big so how much is it possible to add in the bubble",bubble:"left"}])
  const bottomRef = useRef<HTMLDivElement>(null)

  function scrollToBottom(){
    bottomRef.current?.scrollIntoView({
      behavior: "smooth",
      block: "end",
    })
  }

  function addToMessageList(e: React.MouseEvent<HTMLButtonElement, MouseEvent>| React.KeyboardEvent<HTMLTextAreaElement>){
    e.preventDefault()
    if(message.trim() !== ""){
        const newMessageList:MessageListType[] = [...(messageList || []),{message:message,bubble:"right"}]
        setMessageList(newMessageList)
        if(pageType === 1)
          setPageType(2)
        setMessage("")
        scrollToBottom()
    }
  }

  return (
    (pageType === 1 ? 
      <div className="flex flex-col h-screen items-center justify-center font-sans">
        <div className = "flex flex-col w-full items-center justify-center gap-4">
          <h1 className="text-3xl font-bold text-zinc-800 dark:text-zinc-200">Ask anything to <b className="text-cyan-600 font-mono">Qwen</b></h1>
          <div className="flex items-center justify-center mt-4 w-full">
            <textarea className="w-1/2 placeholder:text-zinc-500 rounded-2xl p-3 border-2 border-zinc-300 focus:outline-none focus:border-y-cyan-500 focus:border-x-emerald-500" placeholder="Type your message..." value={message||""} onChange={(e)=>{setMessage(e.target.value);}} onKeyDown={(e) => {if(e.key === "Enter" && !e.shiftKey) addToMessageList(e)}} />
            <button className="bg-emerald-600 transition-color duration-400 hover:bg-cyan-600 ml-2 h-12 w-12 rounded-full cursor-pointer" onClick={(e)=>{addToMessageList(e)}}><Image src="/submit.svg" width={80} height={80} className="p-2" alt="Send" /></button>  
          </div>  
        </div>
      </div>
      :
      <div className="flex flex-col h-screen font-mono">
        <ChatBubbles messageList={messageList}/>
        <div ref={bottomRef} className="pb-30 text-center text-sm">Generated by Qwen</div>
        <div className="fixed bg-slate-50/10 py-2 bottom-0 w-full flex items-center justify-center">
            <textarea className="w-3/4 lg:w-1/2 bg-slate-700 rounded-2xl p-3 border-2 border-zinc-300 focus:outline-none focus:border-y-cyan-500 focus:border-x-emerald-500" placeholder="Type your message..." value={message||""} onChange={(e)=>setMessage(e.target.value)} onKeyDown={(e) => {if(e.key === "Enter" && !e.shiftKey) addToMessageList(e)}} />
            <button className="bg-emerald-600 transition-color duration-400 hover:bg-cyan-600 ml-2 h-12 w-12 rounded-full cursor-pointer" onClick={(e)=>{addToMessageList(e)}}><Image src="/submit.svg" width={80} height={80} className="p-2" alt="Send" /></button>
        </div>
      </div>
    )
  )
}

export default ChatPage